<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav">
    <div class="block-content">
    	<?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        
        <?php if($this->canShowOptions()): ?>            
            <dl id="narrow-by-list" class="accordion">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                    <dt class="<?php if($_filter->getName() == "Vehicle Type" || $_filter->getName() == "Model Type" || $_filter->getName() == "SubDetail") echo "no-display" ?>"><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd class="<?php if($_filter->getName() == "Vehicle Type" || $_filter->getName() == "Model Type" || $_filter->getName() == "SubDetail") echo "no-display" ?>"><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
             </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
       
    </div>
</div>
<?php endif; ?>