<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */

$_filters = $this->getFilters();

$currentUrl = Mage::helper('core/url')->getCurrentUrl();

if (preg_match('/^(.*)([\&|\?]brand=([a-z]*))(.*)$/', $currentUrl, $matches)) {
    // Mage::log(print_r($matches, true));
    $currentUrl = $matches[1] . $matches[4];
}
if (strstr($currentUrl, '?')) {
    $avsBrandUrl  = $currentUrl . '&brand=avs';
    $lundBrandUrl = $currentUrl . '&brand=lund';
} else {
    $avsBrandUrl  = $currentUrl . '?brand=avs';
    $lundBrandUrl = $currentUrl . '?brand=lund';
}

?>
<?php if ($this->canShowBlock()): ?>
<div class="block block-layered-nav">
    <div class="block-content">
    	<?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <?php if ($this->getRequest()->getParam('brand')): ?>
                <div class="actions"><a href="<?php echo $this->getClearUrl() . "?brand=" . $this->getRequest()->getParam('brand') ?>">
                    <?php echo $this->__('Clear All') ?></a>
                </div>
            <?php else: ?>
                <div class="actions">
                    <a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        
        <?php if ($this->canShowOptions()): ?>            
            <dl id="narrow-by-list" class="accordion">
                <?php foreach ($_filters as $_filter): ?>
                    <?php if($_filter->getItemsCount()): ?>
                        <dt class="<?php if($_filter->getName() == "Vehicle Type" || $_filter->getName() == "Model Type" || $_filter->getName() == "SubDetail") echo "no-display" ?>">
                            <?php echo $this->__($_filter->getName()) ?>
                        </dt>
                        <dd class="<?php if($_filter->getName() == "Vehicle Type" || $_filter->getName() == "Model Type" || $_filter->getName() == "SubDetail") echo "no-display" ?>">
                            <?php echo $_filter->getHtml() ?>
                        </dd>
                    <?php endif; ?>
                <?php endforeach; ?>

                <dt class="first odd"><?php echo $this->__('BRANDS') ?></dt>
                <dd class="first odd">
                    <ol>
                        <li>
                            <a rel="nofollow" href="<?php echo $avsBrandUrl; ?>" class="amshopby-attr"><?php echo $this->__('AVS') ?></a>
                        </li>
                        <li>
                            <a rel="nofollow" href="<?php echo $lundBrandUrl; ?>" class="amshopby-attr"><?php echo $this->__('Lund') ?></a>
                        </li>
                    </ol>
                </dd>

             </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
       
    </div>
</div>
<?php endif; ?>