<?php
$_helper = $this->helper('catalog/output');
$storeCategory = Mage::getModel('catalog/category')
                    ->load(Mage::app()->getStore()->getRootCategoryId());

$subCategories  = $storeCategory
                    ->getChildrenCategories()
                    ->clear()
                    ->addIsActiveFilter()
                    ->addAttributeToSelect('*');

$sortedCats = [];
foreach ($subCategories as $_category)
    $sortedCats[$_category->getName()] = $_category;

ksort($sortedCats, SORT_STRING);

$imageHeight = 144;
$imageWidth = 144;
?>

<div class="product-categories clearfix">
    <div class="container">
        <h2 class="title"><?php echo $this->__('Product Categories') ?></h2>
        <div class="clearfix">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-categories-image-block')->toHtml();  ?>
            <div class="right-section">
                <ul>
                    <?php $i = 0 ?>
                    <?php foreach ($subCategories as $_category): ?>
                        <?php
                        $_imgHtml = "";
						$image_url = Mage::getModel("imageresize/resize")->getResizedImageHome($imageWidth, $imageHeight, Mage::getModel('catalog/category')->load($_category->getId())->getSmallImage());
                        $_imgHtml = '<img src="' .$image_url.'" alt="' . $this->escapeHtml($_category->getName()) . '" title="' . $this->escapeHtml($_category->getName()) . '" />';
                        ?>
                        
                        <?php if ($i++ % 2 == 0): ?>
                            <li>
                            <?php endif; ?>

                            <div class="list-devider">
                                <div class="image">
                                    <?php echo $_imgHtml ?>
                                </div>
                                <a href="<?php echo $_category->getUrl() ?>?brand=lund"><?php echo $_category->getName() ?></a>
                            </div>

                            <?php if ($i % 2 == 0): ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>