<div class="social-gallery-page">
<script src="//assets.juicer.io/embed-no-jquery.js" type="text/javascript"></script>
<link href="//assets.juicer.io/embed.css" media="all" rel="stylesheet" type="text/css" />
<ul class="juicer-feed" data-feed-id="lund" data-after="translateJuicer()"></ul>

<script src="<?php echo $this->getSkinUrl("js/masonry-docs.min.js") ?>"></script>
<script type="text/javascript">
	function translateJuicer() {
		jQuery('.j-paginate').text("Load More in another Language")
	}
	
jQuery(document).ready(function($) {
	setInterval(function(){ 
	jQuery('.juicer-feed.slider .slick-track').masonry({
	  itemSelector: '.social-gallery-page .juicer-feed.slider li.feed-item',
	  percentPosition: true,
	});
	}, 500);
	
});
</script>
</div>
