<?php
    $_productCollection = $this->getLoadedProductCollection()->clear();
    // var_dump((string)$_productCollection->getSelect());exit;
    $_helper            = $this->helper('catalog/output');
    $_compareHelper     = $this->helper('catalog/product_compare');
    $_items             = $_compareHelper->getItemCount() > 0 ? $_compareHelper->getItemCollection() : null;
?>

<?php if ($_items): ?>
    <div class="clearfix compare-link">
        <a href="javascript:void(0)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Compare Products')) ?>" class="comapre-link-product" onclick="popWin('<?php echo $_compareHelper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">
            <?php echo $this->__('Compare Products') ?>
        </a>
    </div>
<?php endif; ?>

<?php if(!$_productCollection->getSize()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div class="category-products">

<?php 
    echo $this->getToolbarHtml();
    // List mode
    if ($this->getMode() !== 'grid'):
        $_iterator = 0; 
?>
        <ol class="products-list" id="products-list">
        <?php foreach ($_productCollection as $_product): ?>
            <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <?php // Product description ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
                            </a>
                        </h2>

                        <?php 
                            if($_product->getRatingSummary())
                                echo $this->getReviewsSummaryHtml($_product);
                        
                            echo $this->getPriceHtml($_product, true) 
                        ?>

                        <?php if($_product->isSaleable()): ?>
                            <p><button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>

                        <div class="desc std">
                            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

<?php 
    else:
        // Grid Mode
        $_collectionSize = $_productCollection->getSize();
        $_columnCount    = $this->getColumnCount();
?>
        <ul class="products-grid">
        <?php $i = 0; foreach ($_productCollection as $_product): ?>
        
            <li class="item<?php if (($i - 1) % $_columnCount === 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() . "?brand=lund" ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(276, 170); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                
                <?php if ($_product->getData('brand')): ?>         
                	<?php if ($_product->getResource()->getAttribute('brand')->getFrontend()->getValue($_product) === 'AVS'): ?>
                    	<p><img src="<?php echo $this->getSkinUrl("images/avs-pro-logo.png") ?>" /></p>
                    <?php elseif ($_product->getResource()->getAttribute('brand')->getFrontend()->getValue($_product) === 'Lund'): ?>
						<p><img src="<?php echo $this->getSkinUrl("images/lund-small-logo.png") ?>" /></p>
                    <?php endif;?>
				<?php endif;?>
                                
                <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() . "?brand=lund" ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </h2>
                
                <div class="desc std">
                	<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                </div>
              
                <?php echo $this->getPriceHtml($_product, true); ?>
                <ul class="add-to-links">
                	<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                    	<li>
                            <a href="<?php echo $_compareUrl ?>" class="link-compare">
                                <?php echo $this->__('Compare') ?> <input name="<?php echo $_helper->productAttribute($_product, $_product->getId()) ?>" type="checkbox" value="" />
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
               
            </li>
       
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>

</div>
<?php endif; ?>
