<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
$productLineId = $_product->getProductLine();
$productLine = Mage::getModel('unleaded_productline/productline')->load($productLineId);

Mage::register('current_product_line', $productLine);

$categoryIds = $_product->getCategoryIds();
$considersList = [];
foreach ($categoryIds as $id) {
    $path = Mage::getModel('catalog/category')->load($id)->getPath();
    $parentIds = explode('/', $path);
    $topParentName = Mage::getModel('catalog/category')->load($parentIds[2])->getName();
    if($topParentName == "MMY")        
        continue;
    $considersList[] = $id;
}
?> 
<?php $_category = Mage::getModel('catalog/category')->load(end($considersList)); ?> 

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">
    <div class="container">
        <div class="product-essential">
            <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <?php echo $this->getBlockHtml('formkey') ?>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>
                <div class="product-img-box"> <?php echo $this->getChildHtml('media') ?> 
                    <div class="car-pic-main">
                        <ul>
                            <?php if ($productLine->getProductLineV01Video()): ?>
                                <li>
                                    <a href="https://www.youtube.com/watch?v=<?php echo $productLine->getProductLineV01Video() ?>">
                                        <img src="<?php echo "http://img.youtube.com/vi/" . $productLine->getProductLineV01Video() . "/maxresdefault.jpg" ?>" />
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($productLine->getProductLineV02Video()): ?>
                                <li>
                                    <a href="https://www.youtube.com/watch?v=<?php echo $productLine->getProductLineV02Video() ?>">
                                        <img src="<?php echo "http://img.youtube.com/vi/" . $productLine->getProductLineV02Video() . "/maxresdefault.jpg" ?>" />
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($productLine->getProductLineV03Video()): ?>
                                <li>
                                    <a href="https://www.youtube.com/watch?v=<?php echo $productLine->getProductLineV03Video() ?>">
                                        <img src="<?php echo "http://img.youtube.com/vi/" . $productLine->getProductLineV03Video() . "/maxresdefault.jpg" ?>" />
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($productLine->getProductLineV04Video()): ?>
                                <li>
                                    <a href="https://www.youtube.com/watch?v=<?php echo $productLine->getProductLineV04Video() ?>">
                                        <img src="<?php echo "http://img.youtube.com/vi/" . $productLine->getProductLineV04Video() . "/maxresdefault.jpg" ?>" />
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($productLine->getProductLineV05Video()): ?>
                                <li>
                                    <a href="https://www.youtube.com/watch?v=<?php echo $productLine->getProductLineV05Video() ?>">
                                        <img src="<?php echo "http://img.youtube.com/vi/" . $productLine->getProductLineV05Video() . "/maxresdefault.jpg" ?>" />
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($productLine->getProductLineV06Video()): ?>
                                <li>
                                    <a href="https://www.youtube.com/watch?v=<?php echo $productLine->getProductLineV06Video() ?>">
                                        <img src="<?php echo "http://img.youtube.com/vi/" . $productLine->getProductLineV06Video() . "/maxresdefault.jpg" ?>" />
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
                <div class="product-shop">
                    <?php echo $this->getChildHtml('vehicle-reference') ?>
                    <div class="product-name">
                        <h1><?php echo $productLine->getName(); ?></h1>
                    </div>

                    <p class="part-code">
                        <?php 
                            echo $this->__("Part Number:") . ' ' . strtoupper($_helper->productAttribute($_product, $_product->getSku(), 'name')) . ' ';

                            if ($_product->getData('color')) {
                                echo '| ' . $this->__("Color:") . ' ' . $_product->getResource()->getAttribute('color')->getFrontend()->getValue($_product);
                            }
                        ?>
                    </p>

                    <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php echo $this->getChildHtml('extrahint') ?>
                    
                    <?php echo $this->getChildHtml('product_configurator'); ?>

                    <?php if (!$this->hasOptions()): ?>
                        <div class="add-to-box">
                            <?php if ($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                        </div>
                        <?php echo $this->getChildHtml('extra_buttons') ?>
                    <?php elseif (!$_product->isSaleable()): ?>
                    <?php endif; ?>
                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <h2 class="choose-package"><?php echo $this->__("Choose Your Options.") ?></h2>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif; ?>

                    <div class="clearer"></div>
                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif; ?>

                    <?php echo $this->getChildHtml('addto') ?>
                    <?php echo $this->getChildHtml('product-visuals') ?>
                    <?php echo $this->getChildHtml('other'); ?>

                </div>
                <div class="clearer"></div>


            </form>
            <script type="text/javascript">
                //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function (button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;

                        if (url) {
                            form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }

                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);

                productAddToCartForm.submitLight = function (button, url) {
                    if (this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }

                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
                //]]>
            </script> 
        </div>
    </div>
    <?php if (Mage::app()->getRequest()->getModuleName() != "review") { ?>

        <div class="pro-over-main">
            <div class="container">
                <div class="pro-head-over">
                    <h2 class="mobi-drop-icon"><?php echo $this->__("Product Overview") ?></h2>      
                    <div class="pro-three-box">
                        <div class="pro-first-part">

                            <?php if ($_product->getISheet()): ?>
                                <div class="car-install-main">
                                    <div class="car-install-head">
                                        <h3><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "isheets/" . $_product->getAttributeText('i_sheet') . ".pdf"; ?>" target="_blank"><?php echo $this->__("Install Instructions") ?></a></h3>
                                    </div>
                                    <div class="four-box-pic">
                                        <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "isheets/" . $_product->getAttributeText('i_sheet') . ".pdf"; ?>" target="_blank">
                                            <img src="<?php echo $this->getSkinUrl("images/four-box.png") ?>" />
                                        </a>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <?php if ($productLine->getProductLineInstallVideo()): ?>
                                <div class="video-first-part">
                                    <div class="car-video-head">
                                        <h3><?php echo $this->__("Install video") ?></h3>
                                    </div>
                                    <div class="four-box-pic">
                                        <iframe width="275" height="232" src="https://www.youtube.com/embed/<?php echo $productLine->getProductLineInstallVideo() ?>" frameborder="0" allowfullscreen></iframe>
                                    </div>
                                </div>
                             <?php else: ?>
                             &nbsp;
                            <?php endif; ?>
                        </div>
                        <?php if ($productLine->getDescription()): ?>
                            <div class="pro-second-part">
                                <div class="description-main">
                                    <div class="description-main-head">
                                        <h3><?php echo $this->__("Description") ?></h3>
                                    </div>
                                    <div class="description-main-lund">
                                        <?php echo $productLine->getDescription() ?>
                                    </div>
                                </div>
                            </div>
                        <?php else: ?>
                             &nbsp;
                        <?php endif; ?>
                        <?php if ($productLine->getProductLineFeatureBenefits()): ?>
                            <div class="pro-third-part">
                                <div class="description-main">
                                    <div class="description-main-head">
                                        <h3><?php echo $this->__("Highlights") ?></h3>
                                    </div>
                                    <div class="description-main-lund">
                                        <?php echo $productLine->getProductLineFeatureBenefits() ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="pro-information-main">
            <div class="container">
                <div class="pro-head-over-information">
                    <h2 class="mobi-drop-icon"><?php echo $this->__("Product Technical Information") ?></h2>      
                    <div class="pro-tech-main">
                        <?php echo $this->getChildHtml('product-legends') ?>


                        <div class="pro-tech-second">
                            <div class="pro-tech-table">
                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                        <td><?php echo $this->__("Part Number") ?></td>
                                        <td><?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?></td>
                                    </tr>          

                                    <?php if ($_product->getData('brand_short_code')): ?>
                                        <tr>
                                            <td><?php echo $this->__("Brand Name") ?></td>
                                            <td><?php echo $_product->getResource()->getAttribute('brand_short_code')->getFrontend()->getValue($_product) ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getUpcCode()): ?>
                                        <tr>
                                            <td><?php echo $this->__("UPC Code") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getUpcCode(), 'upc_code') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getWarranty()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Warranty") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getWarranty(), 'Warranty') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getSoldAs()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Sold As") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getSoldAs(), 'sold_as') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getFlareHeight() && $_product->getResource()->getAttribute('flare_height')->getFrontend()->getValue($_product) != "0.00"): ?>
                                        <tr>
                                            <td><?php echo $this->__("Flare Height") ?></td>
                                            <td><?php echo $_product->getResource()->getAttribute('flare_height')->getFrontend()->getValue($_product) ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getFlareTireCoverage() && $_product->getResource()->getAttribute('flare_tire_coverage')->getFrontend()->getValue($_product) != "0.00"): ?>
                                        <tr>
                                            <td><?php echo $this->__("Flare Tire Coverage") ?></td>
                                            <td><?php echo $_product->getResource()->getAttribute('flare_tire_coverage')->getFrontend()->getValue($_product) ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getData('tube_shape')): ?>
                                        <tr>
                                            <td><?php echo $this->__("Tube Shape") ?></td>
                                            <td><?php echo $_product->getResource()->getAttribute('tube_shape')->getFrontend()->getValue($_product) ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getTubeSize()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Tube Size") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getTubeSize(), 'tube_size') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getFinish()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Finish") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getFinish(), 'finish') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getStyle()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Style") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getStyle(), 'style') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getMaterial()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Material") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getMaterial(), 'material') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getMaterialThickness()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Material Thickness") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getMaterialThickness(), 'material_thickness') ?></td>
                                        </tr>
                                    <?php endif; ?>        

                                    <?php if ($_product->getLightPowerRating()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Light Power Rating") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getLightPowerRating(), 'light_power_rating') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getgetLiquidStorageCapacityn()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Liquid Storage Capacityn") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getLiquidStorageCapacityn(), 'liquid_storage_capacityn') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getLiquidStorageCapacityn()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Liquid Storage Capacityn") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getLiquidStorageCapacityn(), 'liquid_storage_capacityn') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getUscountryOrigin()): ?>
                                        <tr>
                                            <td><?php echo $this->__("USCountry Of Origin") ?></td>
                                            <td><?php echo $_helper->productAttribute($_product, $_product->getUscountryOrigin(), 'uscountry_origin') ?></td>
                                        </tr>
                                    <?php endif; ?>





                                </table>

                            </div>
                        </div>

                        <div class="pro-tech-third">
                            <div class="pro-tech-box">
                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                
                                	
									<?php if ($_product->getBoxStyle() || $_product->getBoxOpeningType() || $_product->getInteriorBoxDimensions()): ?>
                                    <tr>
                                        <td><?php echo $this->__("Storage Box Details") ?></td>

                                        <td>&nbsp;</td>
                                    </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getBoxStyle()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Box Style") ?></td>

                                            <td><?php echo $_helper->productAttribute($_product, $_product->getBoxStyle(), 'box_style') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getBoxOpeningType()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Box Opening Type") ?></td>

                                            <td><?php echo $_helper->productAttribute($_product, $_product->getBoxOpeningType(), 'box_opening_type') ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ($_product->getInteriorBoxDimensions()): ?>
                                        <tr>
                                            <td><?php echo $this->__("Interior Box Dimensions") ?></td>

                                            <td><?php echo $_helper->productAttribute($_product, $_product->getInteriorBoxDimensions(), 'interior_box_dimensions') ?></td>
                                        </tr>
                                    <?php endif; ?>


                                        <tr>
                                            <?php if (($_product->getDimA() && $_product->getDimA() != "0.00") || ($_product->getDimB() && $_product->getDimB() != "0.00") || ($_product->getDimC() && $_product->getDimC() != "0.00") || ($_product->getDimD() && $_product->getDimD() != "0.00") || ($_product->getDimE() && $_product->getDimE() != "0.00") || ($_product->getDimF() && $_product->getDimF() != "0.00") || ($_product->getDimG() && $_product->getDimG() != "0.00")): ?>
                                            <td class="bg-thead">					
                                                <?php echo $this->__("Product Specifications") ?>
                                            </td>
                                            <?php endif; ?>
                                            <td class="bg-thead">
												<?php if ($_product->getWeight() || $_product->getHeight() || $_product->getWidth() || $_product->getLength()): ?>
                                                <?php echo $this->__("Shipping Specifications") ?>
                                                <?php endif; ?>
                                            </td>
                                        </tr>

                                    <tr>
                                        <?php if (($_product->getDimA() && $_product->getDimA() != "0.00") || ($_product->getDimB() && $_product->getDimB() != "0.00") || ($_product->getDimC() && $_product->getDimC() != "0.00") || ($_product->getDimD() && $_product->getDimD() != "0.00") || ($_product->getDimE() && $_product->getDimE() != "0.00") || ($_product->getDimF() && $_product->getDimF() != "0.00") || ($_product->getDimG() && $_product->getDimG() != "0.00")): ?>
                                            <td class="padding-none">
                                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                        <?php if ($_product->getDimA() && $_product->getDimA() != "0.00"): ?>
                                                            <tr class="border-main-bottom">
                                                                <td><?php echo $this->__("DIM_A") ?></td>
                                                                <td><?php echo $_helper->productAttribute($_product, $_product->getDimA(), 'dim_a') ?></td>
                                                            </tr>
                                                        <?php endif; ?>

                                                        <?php if ($_product->getDimB() && $_product->getDimB() != "0.00"): ?>
                                                            <tr class="border-main-bottom">
                                                                <td><?php echo $this->__("DIM_B") ?></td>
                                                                <td><?php echo $_helper->productAttribute($_product, $_product->getDimB(), 'dim_b') ?></td>
                                                            </tr>
                                                        <?php endif; ?>

                                                        <?php if ($_product->getDimC() && $_product->getDimC() != "0.00"): ?>
                                                            <tr class="border-main-bottom">
                                                                <td><?php echo $this->__("DIM_C") ?></td>
                                                                <td><?php echo $_helper->productAttribute($_product, $_product->getDimC(), 'dim_c') ?></td>
                                                            </tr>
                                                        <?php endif; ?>

                                                        <?php if ($_product->getDimD() && $_product->getDimD() != "0.00"): ?>
                                                            <tr class="border-main-bottom">
                                                                <td><?php echo $this->__("DIM_D") ?></td>
                                                                <td><?php echo $_helper->productAttribute($_product, $_product->getDimD(), 'dim_d') ?></td>
                                                            </tr>
                                                        <?php endif; ?>
                                                        <?php if ($_product->getDimE() && $_product->getDimE() != "0.00"): ?>
                                                            <tr class="border-main-bottom">
                                                                <td><?php echo $this->__("DIM_E") ?></td>
                                                                <td><?php echo $_helper->productAttribute($_product, $_product->getDimE(), 'dim_e') ?></td>
                                                            </tr>
                                                        <?php endif; ?>

                                                        <?php if ($_product->getDimF() && $_product->getDimF() != "0.00"): ?>
                                                            <tr class="border-main-bottom">
                                                                <td><?php echo $this->__("DIM_F") ?></td>
                                                                <td><?php echo $_helper->productAttribute($_product, $_product->getDimF(), 'dim_f') ?></td>
                                                            </tr>
                                                        <?php endif; ?>
                                                        <?php if ($_product->getDimG() && $_product->getDimG() != "0.00"): ?>
                                                            <tr>
                                                                <td><?php echo $this->__("DIM_G") ?></td>
                                                                <td><?php echo $_helper->productAttribute($_product, $_product->getDimG(), 'dim_G') ?></td>
                                                            </tr>
                                                        <?php endif; ?>
                                                    </table>
                                                </td>
                                            <?php endif; ?>
                                        <td class="padding-none left-border-section"><table width="100%" border="0" cellspacing="0" cellpadding="0">

                                                <?php if ($_product->getWeight()): ?>
                                                    <tr class="border-main-bottom">
                                                        <td class="border-left-bottom"><?php echo $this->__("Weight") ?></td>
                                                        <td><?php echo $_helper->productAttribute($_product, $_product->getWeight(), 'weight') ?></td>
                                                    </tr> 
                                                <?php endif; ?>

                                                <?php if ($_product->getHeight()): ?>     
                                                    <tr class="border-main-bottom">
                                                        <td class="border-left-bottom"><?php echo $this->__("Height") ?></td>
                                                        <td><?php echo $_product->getResource()->getAttribute('height')->getFrontend()->getValue($_product) ?></td>
                                                    </tr>
                                                <?php endif; ?>     


                                                <?php if ($_product->getWidth()): ?>   
                                                    <tr class="border-main-bottom">
                                                        <td class="border-left-bottom"><?php echo $this->__("Width") ?></td>
                                                        <td><?php echo $_product->getResource()->getAttribute('width')->getFrontend()->getValue($_product) ?></td>
                                                    </tr>
                                                <?php endif; ?>  

                                                <?php if ($_product->getLength()): ?>  
                                                    <tr class="border-main-bottom">
                                                        <td class="border-left-bottom"><?php echo $this->__("Length") ?></td>
                                                        <td><?php echo $_product->getResource()->getAttribute('length')->getFrontend()->getValue($_product) ?></td>
                                                    </tr>
                                                <?php endif; ?>  

                                                <tr class="border-main-bottom">
                                                    <td class="border-left-bottom"></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr class="border-main-bottom">
                                                    <td class="border-left-bottom"></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                <tr>
                                                    <td class="border-left-bottom"></td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                            </table></td>
                                    </tr>
                                </table>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('aw.vidtest') ?>
        <div class="review-bg-section clearfix">
            <div class="container">
                <?php echo $this->getChildHtml('review-list') ?>
            </div>
        </div>
        <div class="Product-qa">
            <div class="container">
                <div class="Product-qa-main">
                    <h2 class="mobi-drop-icon"><?php echo $this->__("PRODUCT Q&A") ?></h2>
                    <?php echo $this->getChildHtml('product_additional_data') ?>
                </div>
            </div>
        </div>

        <?php echo $this->getChildHtml('compatible-vehicles') ?>
    <?php } ?>

    <?php if (Mage::app()->getRequest()->getModuleName() == "review") { ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    <?php } ?> 

    <div class="pro-related-avs">
        <div class="container">
            <div><?php echo $this->getChildHtml('related_products') ?></div>
        </div>
    </div>
    <div class="product-collateral">
        <?php echo $this->getChildHtml('upsell_products') ?>

    </div>
</div>
