<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<footer role="contentinfo clearfix">
    <div class="top-footer clearfix">
        <div class="container"> <?php echo $this->getChildHtml('footer-lund-block') ?>
            <div class="footer-top-right"> <?php echo $this->getChildHtml('footer.newsletter') ?> </div>
        </div>
    </div>
    <div class="bottom-footer clearfix">
        <div class="container">
            <?php echo $this->getChildHtml('footer-more-info-links') ?>
            <?php echo $this->getChildHtml('footer-customer-service-links') ?>
            <?php echo $this->getChildHtml('footer-connect') ?>
            <?php echo $this->getChildHtml('footer-contact-details') ?>
        </div>
        <address class="clearfix">
        <?php echo $this->getCopyright() ?> <span><a href="/info/terms-of-use"><?php echo $this->__("Terms & Conditions") ?></a> <a href="/info/privacy-policy"><?php echo $this->__("Privacy Statement") ?></a> <a href="<?php echo $this->getUrl("catalog/seo_sitemap/category") ?>"><?php echo $this->__("Sitemap")?></a></span>
        </address>
    </div>
</footer>
<?php echo $this->getChildHtml('lund.chat.dropin'); ?>
<?php echo $this->getChildHtml('lund.chat.tracking'); ?>

<div class="chat-main-banner">
<div class="container">
<div class="chat-now-banner"><a onclick="javascript:window.open('http://dm5.contactatonce.com/CaoClientContainer.aspx?MerchantId=57316&amp;Providerid=3766&amp;PlacementId=15&amp;OriginationUrl='+encodeURIComponent(location.href),'','resizable=yes,toolbar=no,menubar=no,location=no,scrollbars=no,status=no,height=400,width=600');return false;" href="#">Chat Now</a></div>
</div>
</div>