<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<div class="top-section clearfix">
	<div class="container">
    	<div class="where-to-buy"><a href="/info/dealer-locator"><em class="fa fa-loaction"></em> <?php echo $this->__("Where To Buy") ?></a></div>
    	<?php echo $this->getChildHtml('header-top-brands') ?>
        <div class="shop-brand">
        	<a href="javascript:void(0)"><?php echo $this->__("Shop Brand") ?></a>
        </div>
    	
    </div>
</div>
<div class="header-bg-section clearfix">
    <div class="container">
    	<div class="tablet-menu">
        	<a href="javascript:void(0)" onclick="jQuery('.navbar.navbar-default').toggle();"><?php echo $this->__("Menu") ?></a>
        </div>
        <div class="logo-section">
            <?php if ($this->getIsHomePage()):?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
        </div>
        <div class="header-right">
            <div class="header-right-top clearfix">                
                <div class="login-section">
                    <ul class="custom-login">
                        <li><a href="/info/customer-care"><?php echo $this->__("Customer Service") ?></a></li>
                        <li>
                        	<?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                            	<a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo $this->__("Login or Register") ?></a>
                            <?php else: ?>
                            	<a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>"><?php echo $this->__('Logout') ?></a>
                            <?php endif; ?>
                        </li>
                    </ul>
                    <div class="ulvehicle-navi">
                    	<?php echo $this->getChildHtml('ulvehicle'); ?>
                    </div>
                    </div>
            </div>
            <div class="header-right-bottom clearfix"> 
            	<div class="tablet-menu">
                	<a href="javascript:void(0)" onclick="jQuery('.navbar.navbar-default').toggle();"><?php echo $this->__("Menu") ?></a>
                </div>
                <div class="mobile-search">
                	<a href="javascript:void(0)"><span class="fa fa-search"></span></a>
                </div>
			<?php echo $this->getChildHtml('topMenu') ?> 
			<?php echo $this->getChildHtml('topSearch') ?> </div>
        </div>
    </div>
</div>
<div class="our-product-navi">
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/our-products.phtml')->toHtml(); ?>
</div>
<?php echo $this->getChildHtml('select-vehicle') ?>
