<?php
    $_helper    = Mage::helper('catalog/category');
    $categories = Mage::getResourceModel('catalog/category_collection')
                    ->addFieldToFilter('name', ['in' => ['AVS', 'Lund']]);

    $imageHeight = 52;
    $imageWidth  = 92;

    $sortCats = [];
    foreach ($categories as $category) {
        $subCategories = $category
                            ->getChildrenCategories()
                            ->addIsActiveFilter()
                            ->addAttributeToSelect('*');

        foreach ($subCategories as $_category) 
            $sortedCats[$_category->getName()] = $_category;
        
    }

    ksort($sortedCats, SORT_STRING);
?>

<div class="product-navigation product-show">
    <div class="container">
        <div class="menu-left-content">
            <ul>
                <?php
                    foreach ($sortedCats as $_category):
                        $image_url = Mage::getModel("imageresize/resize")->getResizedImage($imageWidth, $imageHeight, Mage::getModel('catalog/category')->load($_category->getId())->getThumbnail());

                        $categoryUrl = $_helper->getCategoryUrl($_category);
                ?>
                        <li>
                            <div class="catrgory-navigation">
                                <a href="<?php echo $categoryUrl ?>" class="category-image" data-category="<?php echo $_category->getId(); ?>">
                                    <img alt="<?php echo $_category->getName() ?>" src="<?php echo $image_url ?>" />
                                </a>
                                <div class="menu-details">
                                    <div class="menu-title"><a href="<?php echo $categoryUrl ?>"><span><?php echo $_category->getName() ?></span></a></div>
                                    <div class="menu-description"><?php echo $_category->getShortDescription() ?></div>
                                </div>
                            </div>
                        </li>
                <?php
                    endforeach;
                ?>
            </ul>
        </div>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('our-product-top-menu-block')->toHtml(); ?>
    </div>
    <div class="view-all-links">
        <a href="<?php echo $this->getUrl("our-products.html") ?>"><?php echo $this->__("View All Categories") ?></a>
    </div>
</div>