<div class="pro-tech-first">
    <div class="pro-tech-logo">
        <div class="pro-tech-logo-main">
            <h3><?php echo $this->__("legend") ?></h3>
        </div>
        <div class="pro-logo-tech">
            <ul>
                <li>
                    <div class="easy-logo-left"><img src="<?php echo $this->getSkinUrl("images/legend-icons/drilling-required.png") ?>" /></div>
                    <div class="pro-great"><?php echo $this->__("Drilling is Required") ?></div>
                </li>
                <li>
                    <div class="easy-logo-left"><img src="<?php echo $this->getSkinUrl("images/legend-icons/drilling-not-required.png") ?>" /></div>
                    <div class="pro-great"><?php echo $this->__("Drilling is not Required") ?></div>
                </li>
                <li>
                    <div class="easy-logo-left"><img src="<?php echo $this->getSkinUrl("images/legend-icons/oversized-shipping.png") ?>" /></div>
                    <div class="pro-great"><?php echo $this->__("Oversized shipping is Required") ?></div>
                </li>
            </ul>
        </div>
    </div>
</div>