<?php 
$_helper        = $this->helper('catalog/output');
$_product       = Mage::registry('current_product');
$currentVehicle = Mage::getSingleton('core/cookie')->get('currentVehicle');

$currentVehicle = str_replace('_', '-', str_replace('-', ' ', $currentVehicle));

if ($currentVehicle): 
    $garage = $this->getGarageVehicles();
?>
    <div class="product-vehicle-container">
        <?php echo $this->__("This Product Fits: ") ?>
        <div class="current-product-vehicle"><?php echo $currentVehicle ?></div>
        <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <div class="change-vehicle">
                <button class="button add-vehicle" type="button">
                    <span>
                        <span>
                            <?php echo $this->__('Change Vehicle') ?>
                        </span>
                    </span>
                </button>
            </div>
            <?php if (count($garage) >= 1): ?>
                <div class="additional-vehicles">
                    <div class="ul-vehicles">
                        <div class="vehicle-title"><?php echo $this->__("Stored Vehicles") ?></div>
                        <ul class="vehicle-list">
                            <?php foreach ($garage as $vehicleId) : ?>
                                <?php $_vehicle = Mage::getModel('vehicle/ulymm')->load($vehicleId) ?>
                                <?php $searchUrl = $this->getSearchQuery($_vehicle); ?>
                                <li class="vehicle-item">
                                    <span class="remove-vehicle">X</span>
                                    <input type="hidden" value="<?php echo $_vehicle->getId() ?>" />
                                    <div class="vehicle-name">
                                        <?php echo $_vehicle->getYear() . " " . $_vehicle->getMake() . " " . $_vehicle->getModel() ?>
                                    </div>
                                    <div class="view-products">
                                        <a class="search-vehicle-products" href="<?php echo $searchUrl ?>"><?php echo $this->__('View Products') ?></a>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                            <li class="add-vehicle-item">
                                <button class="button add-vehicle" type="button">
                                    <span>
                                        <span>
                                            <?php echo $this->__('Add Vehicle') ?>
                                        </span>
                                    </span>
                                </button>
                            </li>
                            <li class="clear-all">
                                <a href="javascript:void(0)" class="clear-garage"><span>X</span><?php echo $this->__('Clear All') ?></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="embedded-vehicle-selector">
                    <?php echo $this->getChildHtml('select-vehicle-embedded') ?>
                </div>
            <?php else: ?>
                <div class="additional-vehicles">
                    <div class="ul-vehicles">
                        <ul class="vehicle-list">
                            <li class="add-vehicle-item">
                                <button class="button add-vehicle" type="button">
                                    <span>
                                        <span>
                                            <?php echo $this->__('Add Vehicle') ?>
                                        </span>
                                    </span>
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="embedded-vehicle-selector">
                    <?php echo $this->getChildHtml('select-vehicle-embedded') ?>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <div class="additional-vehicles">
                <div class="ul-vehicles">
                    <div class="vehicle-title"><?php echo $this->__("Stored Vehicles") ?></div>
                    <ul class="vehicle-list">
                        <?php foreach ($garage as $vehicleId) : ?>
                            <?php $_vehicle = Mage::getModel('vehicle/ulymm')->load($vehicleId) ?>
                            <?php $searchUrl = $this->getSearchQuery($_vehicle); ?>
                            <li class="vehicle-item">
                                <span class="remove-vehicle">X</span>
                                <input type="hidden" value="<?php echo $_vehicle->getId() ?>" />
                                <div class="vehicle-name">
                                    <?php echo $_vehicle->getYear() . " " . $_vehicle->getMake() . " " . $_vehicle->getModel() ?>
                                </div>
                                <div class="view-products">
                                    <a class="search-vehicle-products" href="<?php echo $searchUrl ?>"><?php echo $this->__('View Products') ?></a>
                                </div>
                            </li>
                            <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) break; ?>
                        <?php endforeach; ?>
                        <li class="clear-all">
                            <a href="javascript:void(0)" class="clear-garage"><span>X</span><?php echo $this->__('Clear All') ?></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="embedded-vehicle-selector">
                <?php echo $this->getChildHtml('select-vehicle-embedded') ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>