<?php
$vehicles = Mage::getModel("vehicle/ulymm")->getCollection()->addFieldToSelect('year');
$years = [];
foreach ($vehicles as $_vehicle) {
    if (!in_array($_vehicle->getYear(), $years)) {
        $years[] = $_vehicle->getYear();
    }
}
?>
<div class="add-vehicle-modal-title"><?php echo $this->__("Select Your Vehicle") ?></div>
<div class="vehicle-selector-group">
    <div class="vehicle-year-selector vehicle-selector">
        <select class="vehicle-year" id="vehicle-year-embeded">
            <option value="0"><?php echo $this->__("Select Year") ?></option>
            <?php foreach ($years as $year): ?>
                <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="vehicle-make-selector vehicle-selector">
        <select class="vehicle-make" disabled="" id="vehicle-make-embeded">
            <option value="0"><?php echo $this->__("Select Make") ?></option>
        </select>
    </div>
    <div class="vehicle-model-selector vehicle-selector">
        <select class="vehicle-model" disabled="" id="vehicle-model-embeded">
            <option value="0"><?php echo $this->__("Select Model") ?></option>
        </select>
    </div>
    <a href="" class="button" id="add-vehicle-to-garage">
        <span>
            <span>
                <?php echo $this->__("GO!") ?>
            </span>
        </span>
    </a>
</div>
<script type="text/javascript">
    jQuery(document).ready(function () {

        jQuery('#add-vehicle-to-garage').on('click', function (e) {
            e.preventDefault();
            if (jQuery('#vehicle-year-embeded').val() !== "0" && jQuery('#vehicle-make-embeded').val() !== "0" && jQuery('#vehicle-model-embeded').val() !== "0") {
                var year = jQuery('#vehicle-year-embeded').val();
                var make = jQuery('#vehicle-make-embeded').val();
                var model = jQuery('#vehicle-model-embeded').val();
                var brand = "";
                
                <?php if ($this->getRequest()->getParam('brand')): ?>
                    brand = "<?php echo $this->getRequest()->getParam('brand') ?>";
                <?php endif; ?>
                    
                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                    var customerId = '<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId() ?>';
                <?php else: ?>
                    var customerId = '<?php echo Mage::getSingleton('core/cookie')->get('guestUnique') ?>';
                <?php endif; ?>
                        
                jQuery.post("<?php echo Mage::getUrl('vehicle/index/addvehicleandredirect/') ?>", {year: year, make: make, model: model, brand: brand, customerId: customerId},
                function (data) {
                    window.location.href = data;
                });
            } else {
                alert("Year, Make Or Model Fields can not be empty.");
            }
        });

        jQuery('.vehicle-year').unbind('change').bind('change', function () {
            var yearForMake = this.value;

            jQuery('.vehicle-make').attr('disabled', "");
            jQuery('.vehicle-model').attr('disabled', "");

            jQuery.post("<?php echo Mage::getUrl('vehicle/index/getmakebyyear/') ?>", {year: yearForMake},
            function (data) {
                var makeOptions = jQuery.parseJSON(data);

                var optionsHtml = "<option value='0'>Select Make</option>";

                jQuery.each(makeOptions, function (index, value) {
                    optionsHtml += "<option value='" + value + "'>" + value + "</option>";
                });

                jQuery('.vehicle-make').removeAttr('disabled');
                jQuery('.vehicle-make').html(optionsHtml);
            });
        });

        jQuery('.vehicle-make').unbind('change').bind('change', function () {
            var yearForModel = jQuery('#vehicle-year-embeded').val();
            var makeForModel = this.value;

            jQuery('.vehicle-model').attr('disabled', "");

            jQuery.post("<?php echo Mage::getUrl('vehicle/index/getmodelbymakeandyear/') ?>", {year: yearForModel, make: makeForModel},
            function (data) {
                var makeOptions = jQuery.parseJSON(data);

                var optionsHtml = "<option value='0'>Select Model</option>";

                jQuery.each(makeOptions, function (index, value) {
                    optionsHtml += "<option value='" + value + "'>" + value + "</option>";
                });

                jQuery('.vehicle-model').removeAttr('disabled');
                jQuery('.vehicle-model').html(optionsHtml);
            });
        });
    });
</script>