<?php $_helper = Mage::helper('catalog/category') ?>
<?php
$category = Mage::getResourceModel('catalog/category_collection')
        ->addFieldToFilter('name', 'Our Brands')
        ->getFirstItem();

$categoryId = $category->getId();
?>
<?php $rootCategory = Mage::getModel('catalog/category')->load($categoryId) ?>
<?php $_categories = $rootCategory->getResource()->getChildren($rootCategory, true); ?>

<div class="product-navigation brand-show">
    <div class="container">
        <div class="menu-left-content">
            <ul>
                <?php foreach ($_categories as $_categoryId): ?>
                    <?php $_category = Mage::getModel('catalog/category')->load($_categoryId) ?>
                    <?php $imageHeight = 52; ?>
                    <?php $imageWidth = 92; ?>
                    <?php $image_url = Mage::getModel("imageresize/resize")->getResizedImage($imageWidth, $imageHeight, $_category->getThumbnail()) ?>
                    <li>
                        <div class="catrgory-navigation">
                            <a href="<?php echo $_helper->getCategoryUrl($_category) ?>" class="category-image">
                                <img alt="<?php echo $_category->getName() ?>" src="<?php echo $image_url ?>" />
                            </a>
                            <div class="menu-details">
                                <div class="menu-title"><a href="<?php echo $_helper->getCategoryUrl($_category) ?>"><?php echo $_category->getName() ?></a></div>
                                <div class="menu-description"><?php echo $_category->getShortDescription() ?></div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('our-brand-top-menu-block')->toHtml(); ?>
    </div>
    <div class="view-all-links">
        <a href="<?php echo $this->getUrl("our-brands.html")?>"><?php echo $this->__("View All Categories") ?></a>
    </div>
</div>