<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Vidtest
 * @version    1.5.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $videoId = $this->getVideoId(); ?>
<?php if ($videoId): ?>
    <?php
    $videoIds = $this->getAllVideoIds();
    $videoIds = array_diff($videoIds, (array) $videoId);
    $url = "http://www.youtube.com/embed/{$videoId}?playlist=" . join(',', $videoIds) . "&rel=0";
    ?>
    <iframe width="<?php echo $this->getWidth(); ?>" height="<?php echo $this->getHeight(); ?>" src="<?php echo $url; ?>" frameborder="0" allowfullscreen></iframe>
<?php endif; ?>