<?php
$vehicles = Mage::getModel("vehicle/ulymm")->getCollection()->addFieldToSelect('year');
$years = [];
foreach ($vehicles as $_vehicle) {
    if (!in_array($_vehicle->getYear(), $years)) {
        $years[] = $_vehicle->getYear();
    }
}
rsort($years);
?>
<div class="main-vehicle-section">
    <div class="container">
        <div class="vehicle-top">
            <div class="vehicle-small">
                <div class="select-vehicle-main">Select Your Vehicle</div>
            </div>
            <div class="vehicle-year">
                <div class="select-year-home">
                    <select class="vehicle-year-select" name="name" id="vehicle-year-top">
                        <option value="0"><?php echo $this->__("Select Year...") ?></option>
                        <?php foreach ($years as $year): ?>
                            <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="vehicle-small-make">
                <div class="select-make-home">
                    <select class="vehicle-make" name="vehicle-make" disabled="" id="vehicle-make-top">
                        <option value="0"><?php echo $this->__("Select Make...") ?></option>
                    </select>
                </div>
            </div>
            <div class="vehicle-small-make">
                <div class="select-make-home">
                    <select class="vehicle-model" name="vehicle-model" disabled="" id="vehicle-model-top">
                        <option value="0"><?php echo $this->__("Select Model...") ?></option>
                    </select>
                </div>
            </div>
            <div class="vehicle-small-go" id="add-body-vehicle-to-garage">
                <div class="select-go"><a href=""><?php echo $this->__("GO!") ?></a></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function () {

        jQuery('#add-body-vehicle-to-garage').on('click', function (e) {
            
            e.preventDefault();
            if (jQuery('#vehicle-year-top').val() !== "0" && jQuery('#vehicle-make-top').val() !== "0" && jQuery('#vehicle-model-top').val() !== "0") {
                var year = jQuery('#vehicle-year-top').val();
                var make = jQuery('#vehicle-make-top').val();
                var model = jQuery('#vehicle-model-top').val();

                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                    var customerId = '<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId() ?>';
                <?php else: ?>
                    var customerId = '<?php echo Mage::helper('core/http')->getRemoteAddr() ?>';
                <?php endif; ?>

                jQuery.post("<?php echo Mage::getUrl('ulvehicle/index/addvehicleandredirect/') ?>", {year: year, make: make, model: model, customerId: customerId},
                function (data) {
                    window.location.href = data;
                });
            } else {
                alert("Year, Make Or Model Fields can not be empty.");
            }
        });

        jQuery('.vehicle-year-select').on('change', function () {
            var yearForMake = this.value;

            jQuery('.vehicle-make').attr('disabled', "");
            jQuery('.vehicle-model').attr('disabled', "");

            jQuery.post("<?php echo Mage::getUrl('ulvehicle/index/getmakebyyear/') ?>", {year: yearForMake},
            function (data) {
                var makeOptions = jQuery.parseJSON(data);

                var optionsHtml = "<option value='0'>Select Make</option>";

                jQuery.each(makeOptions, function (index, value) {
                    optionsHtml += "<option value='" + value + "'>" + value + "</option>";
                });

                jQuery('.vehicle-make').removeAttr('disabled');
                jQuery('.vehicle-make').html(optionsHtml);
            });
        });

        jQuery('.vehicle-make').on('change', function () {
            var yearForModel = jQuery('#vehicle-year-top').val();
            var makeForModel = this.value;

            jQuery('.vehicle-model').attr('disabled', "");

            jQuery.post("<?php echo Mage::getUrl('ulvehicle/index/getmodelbymakeandyear/') ?>", {year: yearForModel, make: makeForModel},
            function (data) {
                var makeOptions = jQuery.parseJSON(data);

                var optionsHtml = "<option value='0'>Select Model</option>";

                jQuery.each(makeOptions, function (index, value) {
                    optionsHtml += "<option value='" + value + "'>" + value + "</option>";
                });

                jQuery('.vehicle-model').removeAttr('disabled');
                jQuery('.vehicle-model').html(optionsHtml);
            });
        });
    });
</script>