<?php 
    $_helper  = Mage::helper('catalog/category');
    $category = Mage::getResourceModel('catalog/category_collection')
                    ->addFieldToFilter('name', 'AVS')
                    ->getFirstItem();

    $subCategories  = $category
                        ->getChildrenCategories()
                        ->addIsActiveFilter();
    $imageHeight = 52;
    $imageWidth  = 92;

    $sortedCats = [];
    foreach ($subCategories as $category)
        $sortedCats[$category->getName()] = $category;

    ksort($sortedCats, SORT_STRING);
?>

<div class="product-navigation product-show">
    <div class="container">
        <div class="menu-left-content">
            <ul>
                <?php 
                    foreach ($sortedCats as $_category):
                        $image_url = Mage::getModel("imageresize/resize")->getResizedImage($imageWidth, $imageHeight, Mage::getModel('catalog/category')->load($_category->getId())->getThumbnail());
                ?>
                    <li>
                        <div class="catrgory-navigation">
                            <a href="<?php echo $_helper->getCategoryUrl($_category); ?>" class="category-image">
                                <img alt="<?php echo $_category->getName() ?>" src="<?php echo $image_url ?>" />
                            </a>
                            <div class="menu-details">
                                <div class="menu-title"><a href="<?php echo $_helper->getCategoryUrl($_category); ?>"><span><?php echo $_category->getName() ?></span></a></div>
                                <div class="menu-description"><?php echo $_category->getShortDescription() ?></div>
                            </div>
                        </div>
                    </li>
        <?php endforeach; ?>
            </ul>
        </div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('our-product-top-menu-block')->toHtml(); ?>
    </div>
    <div class="view-all-links">
        <a href="<?php echo $this->getUrl("our-products.html")?>"><?php echo $this->__("View All Categories") ?></a>
    </div>
</div>