<?php
    $_helper  = Mage::helper('catalog/category');
    $category = Mage::getResourceModel('catalog/category_collection')
                ->addFieldToFilter('name', 'Our Brands')
                ->getFirstItem();

    $categoryId = $category->getId();
    $imageHeight = 52;
    $imageWidth  = 92;
    $rootCategory = Mage::getModel('catalog/category')->load($categoryId);
    $_categories = $rootCategory->getResource()->getChildren($rootCategory, true); 
?>
<div class="product-navigation brand-show">
    <div class="container">
        <div class="menu-left-content">
            <ul>
                <?php 
                    foreach ($_categories as $_categoryId):
                        $_category = Mage::getModel('catalog/category')->load($_categoryId);
                        $image_url = Mage::getModel("imageresize/resize")->getResizedImage($imageWidth, $imageHeight, $_category->getThumbnail());
                        
                        $parentCategory = $_category->getParentCategory();
                        if ($parentCategory && $parentCategory->getName() !== 'Default Category') {
                            $brand = strtolower($parentCategory->getName());
                        }
                ?>
                    <li>
                        <div class="catrgory-navigation">
                            <a href="<?php echo $_helper->getCategoryUrl($_category) ?>" class="category-image">
                                <img alt="<?php echo $_category->getName() ?>" src="<?php echo $image_url ?>" />
                            </a>
                            <div class="menu-details">
                                    <input type="hidden" class="catId" value="<?php echo $_category->getId() ?>"/>
                                    <input type="hidden" class="catBrand" value="<?php echo $brand ?>"/>
                                <div class="menu-title"><a href="<?php echo $_helper->getCategoryUrl($_category) ?>"><?php echo $_category->getName() ?></a></div>
                                <div class="menu-description"><?php echo $_category->getShortDescription() ?></div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('our-brand-top-menu-block')->toHtml(); ?>
    </div>
    <div class="view-all-links">
        <a href="<?php echo $this->getUrl("our-brands.html")?>"><?php echo $this->__("View All Categories") ?></a>
    </div>
</div>