<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top') ?>
<?php if ($_menu): ?>
	<nav class="navbar navbar-default navbar-main" role="navigation">
    	<div class="navbar-collapse navbar-main-collapse nav-width-fixed">
        	<div class="tablet-menu-hide">
            	<a href="javascript:void(0)"><span><?php echo $this->__("Menu") ?></span></a>
            </div>
            <div class="where-to-buy">
            	<a href="/info/dealer-locator/"><span><?php echo $this->__("Where To Buy") ?></span></a>
            </div>
            <ul class="nav navbar-nav">
            	<li class="level0 nav-1 level-top parent about-links"><a class="level-top" href="javascript:void(0)"><span><?php echo $this->__("About Us") ?></span></a>
                	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('about-top-block')->toHtml(); ?>
                </li>
               <li class="level0 nav-1 level-top parent our-products-menu hidefor-desktop"><a class="level-top" href="javascript:void(0)"><span><?php echo $this->__("Our Products") ?></span></a>
                	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/our-products.phtml')->toHtml(); ?>
                </li>
                
                <li class="level0 nav-1 level-top parent our-products-menu hidefor-mobile"><a class="level-top" href="javascript:void(0)"><span><?php echo $this->__("Our Products") ?></span></a></li>
                <li class="level0 nav-1 level-top parent about-links our-brand-topnavi"><a class="level-top" href="javascript:void(0)"><span><?php echo $this->__("Our Brands") ?></span></a>
                	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('our-brand-top-block')->toHtml(); ?>
                </li>
                <li class="level0 nav-1 level-top parent our-vehicle-menu"><a class="level-top" href="javascript:void(0)"><span><?php echo $this->__("Select Vehicle") ?></span></a></li>
            </ul>
            <ul class="custom-login">
            	<li>
                	<?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                    	<a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo $this->__("Login or Register") ?></a>
                    <?php else: ?>
                    	<a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>"><?php echo $this->__('Logout') ?></a>
                    <?php endif; ?>
                </li>
                <li><a href="/info/customer-care/"><?php echo $this->__("Customer service") ?></a></li>
            </ul>
        </div>
    </nav>
<?php endif ?> 